import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '../components/navbar/Navbar';
import NavbarWrapper from "@/components/navbar/NavbarWrapper";
import { ClerkProvider } from '@clerk/nextjs'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Footer from "@/components/footer/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        
        {/* <Navbar /> */}
        <NavbarWrapper />
        
        {children}
        <ToastContainer position="top-right" autoClose={3000} />
         <Footer />
      </body>
    </html>
    </ClerkProvider>
  );
}
