import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '../components/navbar/Navbar';
import NavbarWrapper from "@/components/navbar/NavbarWrapper";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Footer from "@/components/footer/Footer";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import ClientWrapper from "./ClientWrapper/page";
//import usePathname from "next/navigation";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  //const pathname = usePathname();
  //const hideLayoutPaths = pathname === '/login' || pathname === '/signup' ;
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        {/* <Provider store={store}> */}
        <ClientWrapper>
          {/* <Navbar /> */}
          <NavbarWrapper />
          {children}
          {/* {children}
          <ToastContainer position="top-right" autoClose={3000} /> */}
          <Footer />
          </ClientWrapper>
        {/* </Provider> */}
      </body>
    </html>
  );
}
